name: "web_app"
mode: "dev"
port: 8890
version: "v1.0.1"
JAVA_HOME: "java_home"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "test_cron"
  max_open_conns: 1
  max_idle_conns: 1
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 20
